import { getIconData, iconToSVG, iconToHTML, replaceIDs } from "@iconify/utils";
import type { IconifyJSON } from "@iconify/types";
import { CUSTOM, iconName, type IconLibrary } from "./model/iconLibrary";
import { svgToIcon } from "./model/svg";

/**
 * mermaid architecture-beta's five built-in icon names, drawn as minimal
 * inline SVGs so the canvas needs no icon pack for plain diagrams.
 */
const BUILTIN: Record<string, string> = {
  server:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><rect x="3" y="4" width="18" height="7" rx="1.5"/><rect x="3" y="13" width="18" height="7" rx="1.5"/><circle cx="7" cy="7.5" r="0.9" fill="currentColor"/><circle cx="7" cy="16.5" r="0.9" fill="currentColor"/></svg>',
  database:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><ellipse cx="12" cy="5.5" rx="8" ry="3"/><path d="M4 5.5v13c0 1.7 3.6 3 8 3s8-1.3 8-3v-13"/><path d="M4 12c0 1.7 3.6 3 8 3s8-1.3 8-3"/></svg>',
  disk: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2.6"/></svg>',
  cloud:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M7 18a4.5 4.5 0 1 1 .8-8.9A6 6 0 0 1 19.5 11 3.5 3.5 0 0 1 18.5 18Z"/></svg>',
  internet:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.5 2.4 4 5.6 4 9s-1.5 6.6-4 9c-2.5-2.4-4-5.6-4-9s1.5-6.6 4-9Z"/></svg>',
};

/** Bundled icon collections, loaded lazily on first use. */
const LOADERS: Record<string, () => Promise<IconifyJSON>> = {
  // Microsoft's own Azure architecture set, generated by
  // `npm run icons:azure`. Their terms, not Archyne's MIT — see NOTICE.
  // Iconify has 231 collections and none of them is this one, so a cloud
  // diagram had no icon for a VNet unless the user went and fetched it.
  azure: () => import("./icons-azure.generated.json").then((m) => m.default as IconifyJSON),
  logos: () => import("@iconify-json/logos").then((m) => m.icons),
  devicon: () => import("@iconify-json/devicon").then((m) => m.icons),
  carbon: () => import("@iconify-json/carbon").then((m) => m.icons),
  tabler: () => import("@iconify-json/tabler").then((m) => m.icons),
  "simple-icons": () => import("@iconify-json/simple-icons").then((m) => m.icons),
};
const loaded = new Map<string, Promise<IconifyJSON>>();
function loadCollection(name: string): Promise<IconifyJSON> | null {
  const loader = LOADERS[name];
  if (!loader) return null;
  if (!loaded.has(name)) loaded.set(name, loader());
  return loaded.get(name)!;
}

/**
 * The icons the open document carries, kept here so rendering an icon needs
 * nothing from the store — which imports this module, and would make a
 * circle of it. The store hands the library over whenever the document
 * changes.
 */
let carried: IconLibrary = {};

export function setCarriedIcons(library: IconLibrary): void {
  carried = library;
}

/**
 * The carried icons as an icon pack, for handing to mermaid.
 *
 * The canvas renders `custom:` icons from the markup directly, but mermaid
 * only knows *packs* — so the preview drew its "?" box for every imported
 * icon while the canvas beside it drew the icon. One diagram, two answers.
 *
 * Memoised on the library object, which the store replaces whenever the
 * icons change, so this converts once per change rather than once per render.
 */
let packed: { from: IconLibrary; pack: IconifyJSON } | null = null;

export function carriedIconPack(): IconifyJSON {
  if (packed?.from === carried) return packed.pack;
  const icons: IconifyJSON["icons"] = {};
  for (const [name, svg] of Object.entries(carried)) {
    const icon = svgToIcon(svg);
    if (icon) icons[name] = icon;
  }
  const pack: IconifyJSON = { prefix: CUSTOM, icons };
  packed = { from: carried, pack };
  return pack;
}

/**
 * Icon references rewritten to names the packs actually hold.
 *
 * Vendors number their icon files, and the number changes between releases:
 * a diagram written elsewhere may say `azure:02068-icon-service-virtual-networks`
 * where this build of the pack calls the same drawing `azure:virtual-networks`.
 * The canvas resolves that by falling back to the readable half of the name;
 * mermaid has no such fallback, so the preview showed a "?" for an icon the
 * canvas had just drawn.
 *
 * Only the vendor's catalogue shape is touched — four or more digits, then
 * their word for "icon" — and only in what is handed to the renderer. The
 * file keeps whatever it says.
 */
const CATALOGUE_REF = /\b([a-z][a-z0-9-]*):(\d{4,}-icon-(?:service-)?[a-z0-9-]+)/gi;

export function normaliseIconRefs(code: string): string {
  // Only the collections this build actually has; a prefix it does not know
  // is left exactly as the author wrote it.
  return code.replace(CATALOGUE_REF, (all: string, prefix: string, name: string) =>
    LOADERS[prefix.toLowerCase()] ? `${prefix}:${iconName(name)}` : all,
  );
}

/**
 * Render an icon name: a built-in ("database"), one from a bundled
 * collection ("logos:aws-s3"), or one the diagram brought with it
 * ("custom:azure-vnet").
 */
export async function getIconHtml(name: string): Promise<string> {
  const sep = name.indexOf(":");
  if (sep < 0) return BUILTIN[name] ?? BUILTIN.server;
  if (name.startsWith(`${CUSTOM}:`)) {
    // Already sanitised on the way into the library; nothing unchecked
    // reaches the page.
    return carried[name.slice(CUSTOM.length + 1)] ?? BUILTIN.server;
  }
  const collectionP = loadCollection(name.slice(0, sep));
  if (!collectionP) return BUILTIN.server;
  try {
    const json = await collectionP;
    const wanted = name.slice(sep + 1);
    // Microsoft renumbers its files between releases, and Mermaid Chart's
    // diagrams name icons by that number (`azure:10001-icon-service-key-vaults`).
    // Falling back to the readable half of the name means such a diagram
    // opens correctly here whichever release either side is carrying.
    const data = getIconData(json, wanted) ?? getIconData(json, iconName(wanted));
    if (!data) return BUILTIN.server;
    const svg = iconToSVG(data, { height: "auto" });
    return iconToHTML(replaceIDs(svg.body), svg.attributes);
  } catch {
    return BUILTIN.server;
  }
}

/**
 * The bundled collections that are also *published* by Iconify.
 *
 * Azure is not one of them — Microsoft ships a zip, not an API — and neither
 * are a diagram's own imported icons. The distinction matters because only a
 * published icon has a public URL, and only a URL can be drawn by a tool
 * that does not have Archyne's packs.
 */
const ON_ICONIFY = new Set(["logos", "devicon", "carbon", "tabler", "simple-icons"]);

/**
 * The public URL for an icon, or null when it has none.
 *
 * Used to turn a chosen icon into mermaid's image shape, which is the only
 * form that renders outside Archyne.
 */
export function iconifyUrl(ref: string): string | null {
  const sep = ref.indexOf(":");
  if (sep < 0) return null;
  const prefix = ref.slice(0, sep);
  const name = ref.slice(sep + 1);
  if (!ON_ICONIFY.has(prefix) || !name) return null;
  return `https://api.iconify.design/${prefix}/${name}.svg`;
}

/**
 * Icon *names* only, generated by `npm run icons:index`.
 *
 * Search must never import the collection packages: they carry full SVG path
 * data and total roughly 6 MB gzipped, so enumerating names that way meant a
 * single keystroke-debounced query downloaded all of them. The index is ~63 KB
 * gzipped and loads once, and a collection is only fetched when an icon it
 * owns is actually rendered.
 */
let namesIndex: Promise<Record<string, string[]>> | null = null;
function loadNamesIndex(): Promise<Record<string, string[]>> {
  namesIndex ??= import("./icon-names.generated.json").then((m) => m.default);
  return namesIndex;
}

async function collectionNames(collection: string): Promise<string[]> {
  if (!LOADERS[collection]) return [];
  return (await loadNamesIndex())[collection] ?? [];
}

/**
 * Words a diagram uses that the icon sets do not.
 *
 * The bundled collections are brand logos and general-purpose glyphs, and
 * they name things after what they *are* rather than after what a cloud
 * vendor calls them. Searching for "vnet" — the everyday word for an Azure
 * virtual network — matched nothing at all, though a dozen usable network
 * and subnet icons were sitting there under other names.
 *
 * These are added to a search, never substituted for it: an exact match
 * still comes first, and the alternatives follow it.
 */
const ALSO_TRY: Record<string, string[]> = {
  vnet: ["network", "vpc", "subnet"],
  "virtual-network": ["network", "vpc"],
  subnet: ["subnet", "network"],
  vpc: ["vpc", "network"],
  nsg: ["firewall", "security"],
  "resource-group": ["group", "folder"],
  "load-balancer": ["load-balancer", "balance"],
  appgateway: ["gateway", "load-balancer"],
  "app-service": ["app", "web"],
  aks: ["kubernetes"],
  blob: ["object-storage", "storage"],
  "storage-account": ["storage", "object-storage"],
  cosmos: ["database", "document"],
  "key-vault": ["vault", "key", "lock"],
  bastion: ["terminal", "ssh"],
  peering: ["network", "connect"],
};

/** The words to look for, the asked-for one first. */
function terms(query: string): string[] {
  // Icon names are hyphenated and queries are typed with spaces, so a search
  // for "virtual networks" was looking for that string, space and all, and
  // could never match `virtual-networks`. Two words matching nothing at all
  // is not a subtlety — it is most of what anyone types.
  const asked = query.replace(/[\s_]+/g, "-");
  const extra = ALSO_TRY[asked] ?? [];
  return [asked, ...extra.filter((t) => t !== asked)];
}

/**
 * Does this icon's name contain the term in a way worth showing?
 *
 * A short query is an acronym, and matching one in the middle of a word is
 * how searching for "nsg" — a network security group — offered
 * `carbon:transgender` before anything useful: the letters are in there. So
 * three characters or fewer must land at the start of a name or of one of
 * its hyphenated parts; longer words may match anywhere, since "network"
 * inside "hybrid-networking" is a real hit.
 */
function matches(name: string, term: string): boolean {
  // Several words are all required, in any order: "networks virtual" is the
  // same request as "virtual networks", and a name that has only one of the
  // two is not what was asked for.
  const parts = term.split("-").filter(Boolean);
  if (parts.length > 1) return parts.every((p) => matches(name, p));
  if (term.length > 3) return name.includes(term);
  return name === term || name.startsWith(`${term}-`) || name.includes(`-${term}`);
}

/**
 * Search every bundled collection; colored `logos` first, monochrome
 * `simple-icons` after. Returns fully-qualified names.
 */
export async function searchIcons(query: string, limit = 60): Promise<string[]> {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const wanted = terms(q);

  // The diagram's own icons first. Somebody who imported an Azure pack is
  // looking for those, not for a glyph that happens to share the word, and
  // there are never many of them.
  const out: string[] = Object.keys(carried)
    // The same rule the collections are held to, rather than a bare
    // `includes`: an imported pack is hundreds of names, and it deserves the
    // multi-word and acronym handling more than the bundled sets do.
    .filter((n) => wanted.some((t) => matches(n, t)))
    .map((n) => `${CUSTOM}:${n}`);
  // The asked-for word across every collection, and only then the
  // alternatives. The loops used to nest the other way round, so a collection
  // that matched an *alternative* came out ahead of one that matched what was
  // actually typed — searching "vpc" led with an Azure hub icon, because the
  // alias "network" hit a collection earlier in the list.
  for (const term of wanted) {
    for (const collection of Object.keys(LOADERS)) {
      const all = await collectionNames(collection);
      const starts = all.filter((n) => n.startsWith(term));
      const contains = all.filter((n) => !n.startsWith(term) && matches(n, term));
      for (const n of [...starts, ...contains]) {
        const full = `${collection}:${n}`;
        if (!out.includes(full)) out.push(full);
      }
    }
    if (out.length >= limit) break;
  }
  return out.slice(0, limit);
}

/** Icons of a collection whose name contains one of the terms. */
export async function iconsByPrefix(
  collection: string,
  terms: string[],
  limit = 120,
): Promise<string[]> {
  const all = await collectionNames(collection);
  const starts = all.filter((n) => terms.some((t) => n.startsWith(t)));
  const contains = all.filter(
    (n) => !terms.some((t) => n.startsWith(t)) && terms.some((t) => n.includes(t)),
  );
  return [...starts, ...contains].slice(0, limit).map((n) => `${collection}:${n}`);
}

/** All bundled collection ids, in search priority order. */
export const ICON_COLLECTIONS = Object.keys(LOADERS);

export const BUILTIN_ICON_NAMES = Object.keys(BUILTIN);
